/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TxnTransactionHashRouteImport } from './routes/txn.$transactionHash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TxnTransactionHashRoute = TxnTransactionHashRouteImport.update({
  id: '/txn/$transactionHash',
  path: '/txn/$transactionHash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/txn/$transactionHash': typeof TxnTransactionHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/txn/$transactionHash': typeof TxnTransactionHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/txn/$transactionHash': typeof TxnTransactionHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/txn/$transactionHash'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/txn/$transactionHash'
  id: '__root__' | '/' | '/txn/$transactionHash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TxnTransactionHashRoute: typeof TxnTransactionHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/txn/$transactionHash': {
      id: '/txn/$transactionHash'
      path: '/txn/$transactionHash'
      fullPath: '/txn/$transactionHash'
      preLoaderRoute: typeof TxnTransactionHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TxnTransactionHashRoute: TxnTransactionHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
